name: Deploy to AWS

# 触发条件：当你推送到 main 分支时
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        # 使用别人写好的成熟插件 appleboy/ssh-action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          # 下面是让 GitHub 登录服务器后执行的命令
          script: |
            # 1. 进入项目目录
            cd ~/karasuno-high
            
            # 2. 拉取最新代码
            git pull
            
            # 3. 重新构建并启动 (自动化大军出击!)
            docker compose up -d --build
            
            # 4. 清理没用的旧镜像 (保持服务器干净)
            docker image prune -f